### ISSUE TITLE
Status badges not displaying correctly

### ISSUE THREAD

**Issue by ktamiola** [compute-io/compute.io#1]
This is a minor issue related to the readability of the package description in npm repository. It appears the status badges are not displaying properly at https://www.npmjs.com/package/compute.io

`[![NPM version][npm-image]][npm-url] [![Build Status][travis-image]][travis-url] [![Coverage][coveralls-image]][coveralls-url] [![Dependencies][dependencies-image]][dependencies-url]`

**Comment by kgryte** [comment]
@ktamiola Yes, this is due to NPM considering the README too long and chopping off the badge links. Once I have time, I will try to figure out a solution.
